//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreAden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gelirler
    {
        public int GelirID { get; set; }
        public Nullable<double> Tutar { get; set; }
        public Nullable<int> OdemeTurID { get; set; }
        public Nullable<int> EklemeYapanUserID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> KasayaYansit { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public Nullable<int> Son_Guncelleme_Yapan_User { get; set; }
    }
}
