//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreAden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giderler
    {
        public int GiderID { get; set; }
        public Nullable<double> Tutar { get; set; }
        public Nullable<int> GiderTurID { get; set; }
        public Nullable<int> OdemeTurID { get; set; }
        public Nullable<int> EklemeYapanUserID { get; set; }
        public System.DateTime Tarih { get; set; }
        public string EkAcıklama { get; set; }
        public bool KasayaYansıt { get; set; }

        public override string ToString()
        {
            return $"GiderID: {GiderID}, " +
           $"Tutar: {Tutar}, " +
           $"Gider Tür ID: {GiderTurID}, " +
           $"Ödeme Tür ID: {OdemeTurID}, " +
           $"Ekleyen User: {EklemeYapanUserID}, " +
           $"Tarih: {Tarih:yyyy-MM-dd HH:mm}, " +
           $"Açıklama: {EkAcıklama}, " +
           $"Kasaya Yansıt: {KasayaYansıt}";
        }
    }
}
