//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreAden.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adenEntities : DbContext
    {
        public adenEntities()
            : base("name=adenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Giderler> Giderler { get; set; }
        public virtual DbSet<GiderTur> GiderTur { get; set; }
        public virtual DbSet<Kasa> Kasa { get; set; }
        public virtual DbSet<KasaTip> KasaTip { get; set; }
        public virtual DbSet<LogIslemTur> LogIslemTur { get; set; }
        public virtual DbSet<Loglar> Loglar { get; set; }
        public virtual DbSet<Malzemeler> Malzemeler { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Odemeler> Odemeler { get; set; }
        public virtual DbSet<OdemeTur> OdemeTur { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<SiparisMalzemeler> SiparisMalzemeler { get; set; }
        public virtual DbSet<UrunKategori> UrunKategori { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ViewGiderler> ViewGiderler { get; set; }
        public virtual DbSet<ViewSiparis> ViewSiparis { get; set; }
        public virtual DbSet<ViewSiparisMalzemeleri> ViewSiparisMalzemeleri { get; set; }
        public virtual DbSet<ViewLog> ViewLog { get; set; }
        public virtual DbSet<ViewKasaBilgisi> ViewKasaBilgisi { get; set; }
        public virtual DbSet<Gelirler> Gelirler { get; set; }
        public virtual DbSet<Taksit> Taksit { get; set; }
        public virtual DbSet<TaksitPlan> TaksitPlan { get; set; }
        public virtual DbSet<ViewTaksitler> ViewTaksitler { get; set; }
        public virtual DbSet<View_Gelirler> View_Gelirler { get; set; }
        public virtual DbSet<SiparisLog> SiparisLog { get; set; }
    }
}
