//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreAden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odemeler
    {
        public int OdemelerID { get; set; }
        public int SiparisID { get; set; }
        public int OdemeTuruID { get; set; }
        public string EkAciklama { get; set; }
        public System.DateTime OdemeTarihi { get; set; }
        public Nullable<int> GuncellemeYapanUserID { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public Nullable<double> OdemeTutarı { get; set; }
        public bool KasayaYansit { get; set; }
    }
}
