//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreAden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisLog
    {
        public int SiparisLogID { get; set; }
        public Nullable<int> LogIslemTurID { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> KasaID { get; set; }
        public string Acıklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<double> SiparisTutari { get; set; }
        public Nullable<double> MalzemeTutari { get; set; }
    }
}
