//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreAden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taksit
    {
        public int TaksitID { get; set; }
        public Nullable<int> TaksitPlanID { get; set; }
        public Nullable<int> TaksitNo { get; set; }
        public Nullable<System.DateTime> TaksitVadeTarihi { get; set; }
        public Nullable<double> TaksitTutari { get; set; }
        public string TaksitDurumu { get; set; }
    }
}
