//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreAden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGiderler
    {
        public int GiderID { get; set; }
        public string GiderAd { get; set; }
        public Nullable<double> Tutar { get; set; }
        public string EkAcıklama { get; set; }
        public System.DateTime Tarih { get; set; }
        public string UserAd { get; set; }
        public bool KasayaYansıt { get; set; }
        public string OdemeAdı { get; set; }
        public Nullable<int> GiderTurID { get; set; }
        public Nullable<int> OdemeTurID { get; set; }
        public Nullable<int> EklemeYapanUserID { get; set; }
    }
}
