//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreAden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLog
    {
        public int LogID { get; set; }
        public System.DateTime LogTarihi { get; set; }
        public string LogAcıklama { get; set; }
        public string IslemAd { get; set; }
        public string username { get; set; }
        public int IslemTurID { get; set; }
        public int UserID { get; set; }
    }
}
