//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreAden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTaksitler
    {
        public int Expr1 { get; set; }
        public Nullable<int> TaksitSayisi { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Durum { get; set; }
        public int TaksitID { get; set; }
        public Nullable<int> TaksitPlanID { get; set; }
        public Nullable<int> TaksitNo { get; set; }
        public Nullable<System.DateTime> TaksitVadeTarihi { get; set; }
        public Nullable<double> TaksitTutari { get; set; }
        public string TaksitDurumu { get; set; }
        public int Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public Nullable<System.DateTime> Expr5 { get; set; }
        public Nullable<double> Expr6 { get; set; }
        public string Expr7 { get; set; }
    }
}
