//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreAden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSiparisMalzemeleri
    {
        public int MalzemeID { get; set; }
        public string MalzemeAdı { get; set; }
        public Nullable<double> AlısFiyati { get; set; }
        public Nullable<double> StokMiktari { get; set; }
        public int SiparisID { get; set; }
        public int SiparisMalzemeID { get; set; }
        public Nullable<double> Birim { get; set; }
        public bool StoktanDus { get; set; }
    }
}
