//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreAden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSiparis
    {
        public string MusteriAdSoyad { get; set; }
        public string KategoriAdı { get; set; }
        public string SiparisTanimi { get; set; }
        public Nullable<double> Birim { get; set; }
        public Nullable<double> BirimFiyat { get; set; }
        public Nullable<double> SiparisTutari { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public string OdemeAdı { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public bool SiparisAktifMi { get; set; }
        public bool SiparisTeklifDurumu { get; set; }
        public int SiparisID { get; set; }
        public string UserAd { get; set; }
        public int MusteriID { get; set; }
        public string username { get; set; }
        public int OdemeTurID { get; set; }
        public Nullable<int> UrunKategoriID { get; set; }
    }
}
